import type { Metadata } from "next";
import "./globals.css";
import PrivateRoute from "./components/PrivateRoute";


export const metadata: Metadata = {
  title: "Chat App using Appwrite",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <PrivateRoute/>
      <body>
        {children}
      </body>
    </html>
  );
}
